= qAdocEditor 
José Luis Esteban



// compile: a2x --verbose -d book --icons --dblatex-opts "-T native -P doc.pdfcreator.show=0 -P doc.collab.show=0 -P latex.output.revhistory=0 -P doc.toc.show=1 -P table.title.top" -f pdf  -D __builds/

// compile2: a2x -d book --icons --dblatex-opts "-T native -P doc.pdfcreator.show=0 -P doc.collab.show=0 -P latex.output.revhistory=0 -P doc.toc.show=1 -P table.title.top" -f pdf  -D __builds/

// compile2: a2x --icons --dblatex-opts "-T native -P doc.pdfcreator.show=0 -P doc.collab.show=0 -P latex.output.revhistory=0 -P doc.toc.show=1 -P table.title.top" -f pdf  -D __builds/



== Document info

[width="75%", cols="1v, 2v" , options=""]
|==========================================================
| Writer   |   José Luis Esteban

| Creation date |   2010-09-28

| Revision date |   {docdate} {doctime}

|Version |   

|Document name |   {docname}

|Document file |   {docfile}


|========================================================


== Document modifications
Now (2010-09-28 14:06:05 CEST) it's to early to write with detail all modifications

[cols="1,4", options="header"]
|================
| Date | Modification

| 30/12/2012 | Integrated MQEditor component  https://code.google.com/p/mqeditor/ +
               with line number and codecompletion (more in a future)

| 05/10/2010 |
QUrl links, codding links and a tab to code and decode links

| 05/10/2010 |
Dynamic info generated on click link

| 05/10/2010 |
Run links

| 30/09/2010 |
Filter to generate a temp file and run a command (could be the temp generated file) +
This is better than python embedded filter

| 29/09/2010 |
Now, the temp folder is ++/tmp/adoc++ +
This folder will be created if necessary

| 28/09/2010 | Added  <<python_gen_temp,python_gen_temp>>  on asciidoc extensions

|================


<<<


== TODO

Important::
* Option to save not generating preview
* If file is empty, delete it
* You cannot execute an extra task till previous is finished (*run*)
* ready read standard input -> It has to paint the result, not this message
* Problem with filter and pdf
+
---------
 [jle_temp_and_run]
 -----------
 run:python python_test.py
 out:python_test.txt
 #write:here is the filter.  ##commented because it doesn't work on pdf
 -----------
---------
+
* control p and n gives you the first column ¿¿??
* Wrong highlight when in same line...  _hello_   aaaa _goodbye_
* Links to other documents
** The links would be html links to other pages generated by asciidoc
** To manage these situations, the html links will be modified to .adoc links from editor.
** In case the file doesn't exists, qadoceditor will try to open the html link
* Commands to insert links (to documents, include documents, internal links...), macros, etc..
** Key binding ctrl-m, ctrl-i, ctrl-????
* On editor, jump to internal links
* Change the process proc_compile o crear otro process para run
* check process destruction
* Fast key to switch focus between editor and webkit


Medium::
* Rename file
* On preview, generate an unique name per document (is not enough to use the basename)
* Reports
* Links to internal document
** Orphans
** highlight
* Search in file, search in all files
* Replace in file
* Auto generated section on index with orphans links and orphans documents
* If document is empty on save, delete document
* give a unique identifier to each preview (to avoid conflicts in case of documents with same name)
* More than one link in one line will not work (I suppose). Fix it
* Last generated date and time on pdf. Also auto version info
* Code completion on links
* highlight current editor line
* problem with run and links with --

Low::
* Opening links from webkit with control key, have to open on edit mode
* Document the editor
* Keys movement at emacs style (begin selection, good page down and page up)






== General ideas

* This editor can be used to _write documents_ with asciidoc tool-chain
* It can also be used as a _local wiki_
* _Dinamic reports_ can be managed with this tool easily
* The way to access to all (dynamic reports, documents, run programs), can be designed on pretty pages with links
* You can write and see a quick preview very easily (it will be generated on save action)
* The editor will format the source document based on some _asciidoc style marks_
* This editor will work with ++/tmp/adoc++ directory. On start, all files on this directory will be deleted. +
  This folder will be created (if necessary) on application startup
+
[WARNING]
Compiling documents with _jle_ filters, will need ++/tmp/adoc++ folder. +
Filters will create the directory if it doesn't exists. In any case, consider it in case of problems compiling documents
+
[TIP]
The best way to know the editor, is testing it with real files (like this one)


[[keys_shorcuts]]
== Keys


[TIP]
Some keys are a sequence of keys that have to be pressed in proper order



=== General
[width="100%",cols="1,4",options=""]
|========

| ++ctrl-tab++  |  next tab

| ++ctrl-shift-tab++ | previous tab

| ++ctrl-s++ | to save current document (it will also update the html preview document)

| ++ctrl-u++ | to toggle view mode

| ++ctrl-w++ | to close current tab

| ++ctrl-m, ctrl-c, ctrl-f++ | copy full path file from current tab +
At the moment you can not use this keys if the selected component is an editor

| ++ctrl-m, ctrl-c, ctrl-d++ | <<compiling,Compile>> the current document with command configured on source 

|========


=== Editor

[width="100%",cols="1,4",options=""]
|========

| ++ctrl-enter++ | over a link, it will open the file on edit mode

|========


=== Emacs like keys

[width="100%",cols="1,4",options=""]
|========
| ++ctrl-p++ | Previus line

| ++ctrl-n++ | Next line

| ++ctrl-b++ | Back one character

| ++ctrl-f++ | Forward one character

| ++ctrl-a++ | Begin of line

| ++ctrl-e++ | End of line

| ++ctrl-k++ | Kill end of line _(no copy to clipboard)_

| ++alt-f++ | Forward one word

| ++alt-b++ | Backward one word

| ++alt-p++ | Some lines up

| ++alt-n++ | Some lines down

|========









== Links

Links work on web preview and also on editor

From the editor, you can open the link with +control-click+ or +control-enter+


Path on links::
* If link path start with _/_, then it will be considered as an absolute path
* If not, the path will be considered as a relative path _from the current document path_
* Links work with _QUrl_. +
  _asciidoc_ and _QUrl_ need special codes working with spaces and non _ascii_ symbols. +
  In tab _url_ you have a easy way to convert  ++string -> codded++  and ++codded -> string++

Links to asciidoc documents::
* links can be opened from editor. In this case, links will be always opened on edition mode
* In this example, the link will be opened on view (no edit)
+
---------
link:adoc:testing/link1.adoc[link to view (by default)]
---------
+
produces... link:adoc:testing/link1.adoc[link to view (by default)]
and is shown blue on edit window
+
* Now configured to open (by default as edition).
+
---------
link:eadoc:testing/link1.adoc[link to view]
---------
+
produces... link:eadoc:testing/link1.adoc[link to edit]
and is shown as red on edit window
+
* [red]#A link configured to be opened as view, can be opened as edit pressing *ctrl* key on *click*#

Run link::
* Example
+
-------
link:run:comamnd[text]
-------
+
link:run:ls[ls]
+
* These links are special because they will not expand path automatically
* The ++command current path++ will be the ++application current path++
* Command output will be written on log
* When a run link is executed, the page will be recompiled
+
[WARNING]
++run:++ links don't expand paths +




[WARNING]
When you open a link on edit mode, the preview page will not be generated. +
This is conveniente in order to avoid execution on dynamic pages before expected


=== Asciidoc paths macros
* ++\{indir}++               input file directory name (note 2,5)
* ++\{infile}++              input file name (note 2,5)
* ++\{docfile}++             document file name  (note 5)
* ++\{docdir}++              document input directory name  (note 5)

[TIP]
More information on asciidoc documentation


[[compiling]]
== Compiling the document

* On compile menu, you can select _compile options to build_

* Then you can choose between different options. You will see the command line on bottom box

* You can write the compile command on a comment in your document in a commented line
+
[TIP]
You could copy this command from compile options build
+
-----------
  // compile: a2x --icons ...
  // compile: --dblatex-options " ...
-----------
+
As you can see, you can divide the command in different lines

** When you have the compile line on document, you can also compile directly from menu Compile or using the <<keys_shorcuts, key shortcut>>


== asciidoc extensions

[IMPORTANT]
My +folder+ filter is a soft link to {docdir}/../../filters


[[python_gen_temp]]
=== python_gen_temp (DEPRECIATED)

It's better to use <<jle_temp_and_run,jle_temp_and_run>>

Using::
* A new macro to embedded python code in our documents
+
.Example
----------
 [python_gen_temp]
 --------
 print "* Hola pajarito sin cola"
 print "* Hasta luego cara huevo"
 print "** jajajajajajajaaaaaa"
 --------
 +
 include::temp.txt[]
---------
* This filter, will generate a _temp.py_ with the code inside this block
* It will execute the temp.py file
* The output of this execution, will be written on _temp.txt_
* Both temp files, will be created on document dir
+
[WARNING]
This temporary files will not be deleted
+
* Executing a shell command using this filter...
+
.Executing command (ls -lsh)
-------
 [python_gen_temp]
 ---------
 import os
 pipe = os.popen('ls -lsh')
 lines = pipe.readlines()
 print "----------"  # decoration block
 for line in lines:
     print line
 print "----------"  # decoration block
 ---------
 +
 include::temp.txt[]
---------
+
[IMPORTANT]
The current directory (document directory and temporary files) will be passed to python scripts as first argument
+
* Next code would write the current doc path
+
.Get currend dir
--------
 [python_gen_temp]
 ---------
 import sys

 print "----------"
 print sys.argv[1]
 print "----------"
 ----------
 include::temp.txt[]
--------

Instaling::
The installation is as normal filter extension (see asciidoc documentation)
* On my ++home++ folder I've created the ++.asciidoc++ folder and filters ++/home/user/.asciidoc/filters/python_gen_temp/++
* On this folder there are next files _(generated by this filter)_
+
[python_gen_temp]
---------
import os
pipe = os.popen('ls /home/user/.asciidoc/filters/python_gen_temp/ | grep -v ".*~"')
lines = pipe.readlines()
print "----------"  
##for line in lines:  ##  this is ok, but ls gives as a \n at end
##    print line
print (''.join(lines))
print "----------"  
---------
+
include::temp.txt[]
* Content of python file...
+
---------
include::/home/user/.asciidoc/filters/python_gen_temp/python_gen_temp-filter.py[]
-----------
* Content of conf file...
+
---------
include::/home/user/.asciidoc/filters/python_gen_temp/python_gen_temp-filter.conf[]
-----------




[[jle_temp_and_run]]
=== jle_temp_and_run

Using::
This filter will create a temp file on ++/tmp/adoc++ folder +
You could write a python or shell script for example, and you can run it from same filter and redirect the output to a file to be included on your document

* The filter has two main sections...

* *initialization*
** This is python code
** You can write directly to filter, or you can initialize used vars on this filter:
*** run=
**** A list of tuples with command to execute, file to write the output and flags for this file (this lets you to write several commands on same file)
**** The commands will be executed after creation of temp file
**** You can refer to +file_name+ from +run+
**** The +file_name+ will be created on +/tmp/adoc+ and it will be the current path when executing +run+ commands
**** As run is a list, you can have several commands to run
* *Temp file to create*
** The section starts after +file_name=+ line
** Once the system found the file_name initialization, next lines will be written to this file name
** The file name will be created on +/tmp/adoc+ folder
* You can write on filter just with +print+ python command
* Example
+
.Basic example
-----------
 [jle_temp_and_run]
 ++++++++++++++++++++++++
 run=[('python python_test.py', 'python_test.txt', 'wt')]

 print '**************'
 print 'hello'
 print '**************'

 file_name='python_test.py'
 # this is our testing script
 print '------------'
 print 'writting from a python script '
 print '${docdir}      ${docname}'
 print '------------'
 +++++++++++++++++++++++++

 include::/tmp/adoc/python_test.txt[]
----------

+
[IMPORTANT]
Remember the file will be created on ++/tmp/adoc++ and the current path on _run:_,  will be ++/tmp/adoc++
+
* Here we have the filter output
+
[jle_temp_and_run]
+++++++++++++++++++++
run=[('python python_test.py', 'python_test.txt', 'wt')]

## print '--------------'
## print 'hello'
## print '--------------'

file_name='python_test.py'
# this is our testing script
print '------------'
print 'writing from a python script '
print '${docdir}      ${docname}'
print '------------'
print '+'
+++++++++++++++++++++

* And here we have the document generated by filter included
+
include::/tmp/adoc/python_test.txt[]



Instaling::
The installation is as normal filter extension (see asciidoc documentation)
* On my ++home++ folder I've created the ++.asciidoc++ folder and filters ++/home/user/.asciidoc/filters/jle_temp_and_run/++
* On this folder there are next files _(generated by this filter)_
+
[jle_temp_and_run]
+++++++++++++++++
run=[("echo '--------'",'ls.txt', 'wt'), 
      ("ls /home/maiquel/.asciidoc/filters/", 'ls.txt', 'at'),
      ("echo '--------'",'ls.txt', 'at')]
print ''
+++++++++++++++++
+
include::/tmp/adoc/ls.txt[]
* Content of python file...
+
---------
include::/home/maiquel/.asciidoc/filters/jle_temp_and_run-filter.py[]
-----------
* Content of configuration file...
+
---------
include::/home/maiquel/.asciidoc/filters/jle_temp_and_run-filter.conf[]
-----------


////////
#run:python trick_link.adoc
#out:trick_link.adoc
#write:here is the filter.  ##commented because it doesn't work on pdf
////////////

== Tricks

Dynamic info generated on click link::
* We can have _link_ on our document that produce an output and update in document
+
[jle_temp_and_run]
++++++++++++++
run=[('touch /tmp/adoc/trick_link_result.adoc', 'nothing', 'wt')]
print ''

file_name='trick_link.py'
import time
FILE = open('/tmp/adoc/trick_link_result.adoc', 'wt')
from time import gmtime, strftime
FILE.write('+\n')
FILE.write('----------\n')
FILE.write('Generated: ' + strftime("%a, %d %b %Y %H:%M:%S +0000", gmtime()) + '\n')
FILE.write('Hello, bird with no tail\n')
FILE.write('\n')
FILE.write('----------\n')
FILE.close()
++++++++++++++
+
link:run:python%20/tmp/adoc/trick_link.py[link generating dynamic content on click]
include::/tmp/adoc/trick_link_result.adoc[]
+
* Here is how to do it
+
--------------
 [jle_temp_and_run]
 ++++++++++++++
 run=[('touch /tmp/adoc/trick_link_result.adoc', 'nothing', 'wt')]  <1>
 print ''   <2>

 file_name='trick_link.py'  <3>
 import time
 FILE = open('/tmp/adoc/trick_link_result.adoc', 'wt')
 from time import gmtime, strftime
 FILE.write('+\n')
 FILE.write('----------\n')
 FILE.write('Generated: ' + strftime("%a, %d %b %Y %H:%M:%S +0000", gmtime()) + '\n')  <4>
 FILE.write('Hello, bird with no tail\n')
 FILE.write('\n')
 FILE.write('----------\n')
 FILE.close()
 ++++++++++++++
+
 link:run:python%20/tmp/adoc/trick_link.py[link generating dynamic content on click]  <5>
 include::/tmp/adoc/trick_link_result.adoc[]   <6>

---------------
+
<1> To remove the asciidoc warning, file to include doesn't exist +
    As the script will not be executed on document generation, we don't have the oportunity to receive the output
<2> Write nothing on filter position
<3> The script will be executed on link click. See <6>
<4> In these cases are insteresting to write when the information was generated
<5> Link to generated script
<6> Link to document generated by script
